name = "TrendDecomposition"
uuid = "d73ad930-938d-4709-8eff-50e740f82fcd"
authors = ["Stefan Brinkmann <sdbrinkmann@outlook.com>"]
version = "0.5.0"


[deps]
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Lasso = "b4fcebef-c861-5a0f-a7e2-ba9dc32b180a"

[extensions]
L1MethodsExt = ["Convex", "SCS"]
FusedADMM = ["Lasso"]

[compat]
Convex = "0.16"
Distributions = "0.25"
HypothesisTests = "0.11"
Lasso = "0.7.3"
LinearAlgebra = "1.11"
Optim = "1.13.2"
SCS = "2.4"
SparseArrays = "1.11"
Statistics = "1.11"
Test = "1.11"
julia = "1.11"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Distributions", "Test", "Lasso"]
